[package]
name = "baste64"
authors = ["Matthew Kim"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A base64 codec"

[dependencies]
base64 = "0.22.1"
paste = "1.0.15"
wasm-bindgen = "0.2.93"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[lib]
crate-type = ["cdylib", "rlib"]
