[package]
name = "based64"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
paste = "1.0.15"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
getrandom = { version = "0.2", features = ["js"] }
