name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TARGET: wasm32-unknown-unknown

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust with nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install wasm32-unknown-unknown target
      run: rustup target add ${{ env.TARGET }}


    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Build
      run: cargo build --target=${{ env.TARGET }} --verbose 
      
    - name: Run tests
      run: cargo test --target=${{ env.TARGET }} --verbose
